# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0951f18d337d715a32684ba225c9e9d21bd56915006bf795bb90a3c1699da75836d98feb84627dfd8d575b7fd4ea6b19b11f5fe3aba13d1bdc148cb708edc04e

test:
  secret_key_base: c605b50ebe8ee084460d260257dfc826a77929133a77ba304e728a32680fd1b2eafb53cbce574e405da794b66b607d842403080a78072abf45d985f58e172698

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
